sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"
cache: pip

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install mock; fi
  - pip install flake8
  - pip install .

script:
  - flake8
  - python -m unittest discover tests

notifications:
  email: false
