sudo: false
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 3.7-dev
  - pypy
  - pypy3
cache: pip

matrix:
  allow_failures:
    - python: 3.7-dev
    - python: pypy3

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install mock; fi
  - travis_retry pip install -U pip setuptools wheel twine flake8
  - pip install .

script:
  - flake8
  - python -m unittest discover tests

notifications:
  email: false

# deploy:
#   provider: pypi
#   user: managedbyq
#   password:
#     secure: oCTlYd6hDpkRyArN5cFBoLs5UIqeOXgMDGrgDLpS2m8l9tKMz+hbEK4oTikrZUgmlOrrmG8tWVIXkciyHBI71LVlUp61aSaTo0/SdJIousxSbQT7uI6IUvlvjEBYI+lCk7zjE4Tr9cVOGwtWqrlWRUrGh6b7NhtVRUMRTYGuno/cKCDz3HUde0ITjuroPiFkkdYBXs4xyheKzPgYx0v99XBfC3ELOFBLUzWeJHjNHfNSBkCCt7g5uAMyAuvNiU+PkFzEcsLIN+mGElOJKKDawhaT3/K1sePq9kXtKf5mnwNncq7r74wL0lKJtnCEmzfGZpmPMTJCLzTL1WkTCbkGAExnbnuWvypu/FtHWx+FQNjs9p+UzXleKcELmAzcDfsqmF+lCn8hCf02rTJZgwRlZz1/uQw8ZT1GVyAYywrRt5bedLL4+NHbKh//YA5WU3Y37KAqy1EtL+xX9XJ4So9AbHZ0TjJM8r0i+64p5vMM9HmmZmsssNwnZaAJXDmf4Lb5fG7vGmFmXy78dKRdWxd1dx9/js+3/SbVLNUaty92QoX+ympzElarsQztl0jmb1HeO25X6SUtctdPSqmZfSBjWXDCzf31XdoqTumtetUqzQnV7hcC1bwKZ/HwjlUstGTVvx0UT1387Mq+zY3tMbn4/z+lCqKRGPpE8AevKaK5yeQ=
#   on:
#     tags: true
#     distributions: sdist bdist_wheel
#     python: '3.6'
#     repo: managedbyq/mbq.metrics
