sudo: false
dist: xenial
language: python
cache: pip

python:
  - '3.6'
  - '3.7'

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  include:
    - { python: '3.6', env: TOXENV=lint }

  allow_failures:
    - env: DJANGO=master

install:
  - travis_retry pip install --upgrade pip tox tox-venv tox-travis

script:
  - tox || travis_terminate 1

notifications:
  email: false

deploy:
  provider: pypi
  user: managedbyq
  password:
    secure: oCTlYd6hDpkRyArN5cFBoLs5UIqeOXgMDGrgDLpS2m8l9tKMz+hbEK4oTikrZUgmlOrrmG8tWVIXkciyHBI71LVlUp61aSaTo0/SdJIousxSbQT7uI6IUvlvjEBYI+lCk7zjE4Tr9cVOGwtWqrlWRUrGh6b7NhtVRUMRTYGuno/cKCDz3HUde0ITjuroPiFkkdYBXs4xyheKzPgYx0v99XBfC3ELOFBLUzWeJHjNHfNSBkCCt7g5uAMyAuvNiU+PkFzEcsLIN+mGElOJKKDawhaT3/K1sePq9kXtKf5mnwNncq7r74wL0lKJtnCEmzfGZpmPMTJCLzTL1WkTCbkGAExnbnuWvypu/FtHWx+FQNjs9p+UzXleKcELmAzcDfsqmF+lCn8hCf02rTJZgwRlZz1/uQw8ZT1GVyAYywrRt5bedLL4+NHbKh//YA5WU3Y37KAqy1EtL+xX9XJ4So9AbHZ0TjJM8r0i+64p5vMM9HmmZmsssNwnZaAJXDmf4Lb5fG7vGmFmXy78dKRdWxd1dx9/js+3/SbVLNUaty92QoX+ympzElarsQztl0jmb1HeO25X6SUtctdPSqmZfSBjWXDCzf31XdoqTumtetUqzQnV7hcC1bwKZ/HwjlUstGTVvx0UT1387Mq+zY3tMbn4/z+lCqKRGPpE8AevKaK5yeQ=
  on:
    repo: managedbyq/mbq.metrics
    branch: master
    tags: true
    python: '3.6'
    # admittedly, this condition is a bit silly but we want the deploy to happen
    # on exactly one build, not all py36 builds, and looking for django 1.11 is a cheap
    # way to accomplish that.
    condition: $DJANGO = '1.11'
    distributions: sdist bdist_wheel
