---
version: '3'

services:
  py27:
    build:
      context: .
      dockerfile: Dockerfile-py27
    command: [./test.sh]

  py36:
    build:
      context: .
      dockerfile: Dockerfile-py36

  py37:
    build:
      context: .
      dockerfile: Dockerfile-py37
    command: [./test.sh]

  pypy3:
    build:
      context: .
      dockerfile: Dockerfile-pypy3
    command: [./test.sh]
